### PR TITLE
feat: Add the Loki Bosh release to Bosh.io

### PR DESCRIPTION
**Pull request by ZPascal**
Checklist for submission:

- [x] LICENSE and NOTICE files are up to date
- [x] at least one final release is checked in on the default repo branch (there's a `.final_builds` folder)
- [x] of use to the general community and will be maintained
- [x] github repo must be public
- [x] bosh create-release must run successfully against all final releases (the blobstore needs to be public)
  - if not all final releases are valid, specify a `min_version`
- [x] a README explaining what the repo does
- [x] [optional] deployment manifests/ directory contains example manifest

### CODE REVIEW

**Review by jpalermo — APPROVED** [review]
👍

**Comment by jpalermo** [comment]
The final releases cannot be built currently because the blobstore is a local path under `/tmp` (on your computer I'm guessing?) https://github.com/cloudfoundry-community/loki-boshrelease/blob/main/config/final.yml

Storing the final blobs in the repo is a good option if they are either small or if GIT LFS is enabled for that folder.

Otherwise they'd need to be put into a public S3 or GCS bucket.

**Comment by ZPascal** [comment]
@jpalermo Sorry, I overlooked in the meantime that the repository has no publicly accessible blob storage and uses the local one (the build is handled automatically within [GitHub actions](https://github.com/cloudfoundry-community/loki-boshrelease/actions/runs/7848578817/job/21420018603) and releases a tar archive at the end). I will put it on my agenda. As far as I know, the community has some publicly available GCS/S3 buckets. Do you have any information, on who is responsive for the buckets?

**Comment by jpalermo** [comment]
No idea, but you might be able to ask in the #general channel of the CF Slack.

Something we've done for smaller releases with fewer (and smaller) blobs is to use just a [local path in the repo](https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/blob/master/config/final.yml) and enable git lfs for the repo. Not sure if git lfs is available on the community repo or not though.

**Comment by cunnie** [comment]
@ZPascal Please let us know when you've fixed this so we can resume the publishing job.

**Pull request merged**
