### PR TITLE
add k3s bosh releases

### PR DESCRIPTION
**Pull request by poblin-orange**
Checklist for submission:

- [X] LICENSE and NOTICE files are up to date
- [X] at least one final release is checked in on the default repo branch (there's a `.final_builds` folder)
- [X] of use to the general community and will be maintained
- [X] github repo must be public
- [X] bosh create-release must run successfully against all final releases (the blobstore needs to be public)
  - if not all final releases are valid, specify a `min_version`
- [X] a README explaining what the repo does
- [X] [optional] deployment manifests/ directory contains example manifest

### CODE REVIEW

**Comment by rkoster** [comment]
@poblin-orange could you take a look at EasyCLA?

**Comment by poblin-orange** [comment]
> @poblin-orange could you take a look at EasyCLA?

@rkoster done :-)

**Review by rkoster — APPROVED** [review]

**Comment by jpalermo** [comment]
Sorry about this, we merged this but never ran the pipeline generation script, so nothing was being built and put on bosh.io

Just merged a new PR and noticed the changes. They should show up on bosh.io soon.

**Comment by jpalermo** [comment]
@poblin-orange & @gberche-orange 

I take some of that back. Two of the releases built find, but two of them are failing because the final releases are missing blobs in the blobstore.

`k3s-packages-boshrelease` is failing currently when it gets to release `k3s-packages-1.25.16+k3s4`
`nerdctl-package-boshrelease` is failing when trying to build `k3s-1`

You should be able to reproduce the problem by doing a `bosh create-release PATH_TO_FINAL_RELEASE_YAML_FILE`

If you're unable to restore the missing blobs, you can always just delete the final release yaml files from the repo.

**Pull request merged**
